version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - stock

  app:
    image: stock:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
#      DATABASE_HOST: db
#      DATABASE_PORT: 5432
#      DATABASE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - stock
networks:
  stock:
    external: true
