spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_stock
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
