spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_stock
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://127.0.0.1:8082"
#      client:
#        registration:
#          client-stock:
#            provider: spring
#            client-id: client-stock
#            client-secret: 12345
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/authorized"
#            scope:
#              - openid
#              - profile
#              - read
#              - write
#            client-name: client-stock
#        provider:
#          spring:
#            issuer-uri: "http://127.0.0.1:8082"
